### ISSUE TITLE
Upgrade to 1.9.8 version

### ISSUE THREAD

**Issue by davideprevosto** [darylldoyle/safe-svg#10]
Hi there,
I did install your plugin through composer but I am not able to update it your last version. 

`- The requested package darylldoyle/safe-svg ^1.9.8 exists as darylldoyle/safe-svg[1.9.4, 1.9.5, 1.9.6, 1.9.7, dev-master] but these are rejected by your constraint.`

**Comment by vburlak** [comment]
Hey @davideprevosto 
You could try to add [wpackagist-plugin](https://wpackagist.org) repo to your composer.json and then just
`composer require wpackagist-plugin/safe-svg`

In that case you always will use the latest stable version available at wp.org

**Comment by davideprevosto** [comment]
Thank you for your reply. I will try.
