### ISSUE TITLE
Request: Filter to disable SVG block registration

### ISSUE THREAD

**Issue by Log1x** [darylldoyle/safe-svg#114]
### Is your enhancement related to a problem? Please describe.

Thanks for the excellent plugin. I was wondering if it'd be possible to get a filter to disable registration of the SVG block and category? The simplicity of the plugin is one of it's most attractive features.

Also, it might be worth a separate bug report, but the block registration as-is is enqueueing the frontend assets on every page of my site despite not using the block. Not sure if you're able to reproduce?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@Log1x Thanks for the suggestion! It's already possible to remove blocks from WordPress in a few different ways:

1. Using javascript: https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#removing-blocks
2. Using PHP: https://developer.wordpress.org/reference/functions/unregister_block_type/

I've tested both and they both work to remove the Safe SVG block.

> Also, it might be worth a separate bug report, but the block registration as-is is enqueueing the frontend assets on every page of my site despite not using the block. Not sure if you're able to reproduce

This was reported in a few places and we have a [PR](https://github.com/10up/safe-svg/pull/112) that's been merged to fix this, which should be going out this week in a new release.
