### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [darylldoyle/safe-svg#13]
**Is your enhancement related to a problem? Please describe.**
Now that WordPress 5.8 is released, we'll want to test Safe SVG to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Safe SVG on WordPress 5.8
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by BBerg10up** [comment]
Hey @jeffpaul, this one is good to go. I just wrapped up testing and didn't come across any compatibility issues. One thing to note, I only tested the free version (no upgraded versions).
