### ISSUE TITLE
Safe SVG Icon Block UX Suggestions

### ISSUE THREAD

**Issue by fabiankaegy** [darylldoyle/safe-svg#131]
Whilst working on a site that is using the Plugin, I interacted with the Safe SVG Icon block for the first time and I have some thoughts that could improve the usability :) 

**1. Change the name and or description of the block to be more descriptive**

When I first saw the block, it took me quite a while to figure out why I would want to use the block over just using an Image block to select the SVG. The reason why you would want to use the block over the core image is that it inlines the SVG. So my suggestion is to rename the block to `Inline SVG` or at least add something to the block description and keywords about it rendering the SVG inline. 

**2. Change the block Icon**

Currently the Icon doesn't feel very at home in the editor. It is to bold / weighty compared to other core blocks. I would suggest replacing it with an icon that is more similar to the icon of the Custom HTML block that just says `SVG` or something similar :) 
<img width="253" alt="CleanShot 2023-06-22 at 13 24 46@2x" src="https://github.com/10up/safe-svg/assets/20684594/117bb854-bbf9-407f-a0ae-cc0971605cff">

<img width="110" alt="CleanShot 2023-06-22 at 15 22 15@2x" src="https://github.com/10up/safe-svg/assets/20684594/8a709c5f-3c3d-459f-a786-910fa6f4cbd4">

**3. Refine the "empty" state**

Currently the empty / placeholder state of the block only renders a button which opens the media modal. 
<img width="667" alt="CleanShot 2023-06-22 at 15 18 59@2x" src="https://github.com/10up/safe-svg/assets/20684594/a59f3ade-a270-4a8a-a557-11e1297df718">

This is very different to how all the other media blocks handle this. The image block for example renders a `MediaPlaceholder` which also allows you do drop something into the placeholder directly to upload it etc. 
<img width="666" alt="CleanShot 2023-06-22 at 15 20 29@2x" src="https://github.com/10up/safe-svg/assets/20684594/e631c8cd-6fe6-472e-adf4-723c17d14741">

I think we can do something more similar to that very easily by making use of the [`MediaPlaceholder`](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/media-placeholder) component

**4. Add color controls**

Since the block actually renders an SVG element we have the benefit of being able to style the SVG. One of the most common things we need to do is to be able to change the color of a solid icon. I think it would be great to add the `text` color support so that an SVG that uses the `currentColor` value is able to be modified via the block.

**5. Add dimension controls**

Similar to the image block it would be great to be able to change the size of an icon. And whilst we are at it being able to control margin and padding are also great options to have for this kind of element. (If we add padding we should also add background color support :))

**Comment by bmarshall511** [comment]
@fabiankaegy Took a stab at these, hit everything but the block icon: https://github.com/10up/safe-svg/pull/135

Let me know if this is what you were thinking, wanted to make sure I was on the right path with the implementation. I'll look into updating the block icon next.
