### ISSUE TITLE
Browser Warning Error for svg icon

### ISSUE THREAD

**Issue by t-hamano** [darylldoyle/safe-svg#149]
### Describe the bug

After installing this plugin and opening the block inserter, the following error is output to the browser console:

```
react-dom.js?ver=18.2.0:73 Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
```

This SVG is rendered as a React element, so I think it needs to be changed to `fillRule`

https://github.com/10up/safe-svg/blob/0e895dadd327df9849f827d858675e9be8b948ef/includes/blocks/safe-svg/index.js#L33

### Steps to Reproduce

You may need to change `SCRIPT_DEBUG` to `true` to reproduce this problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Thanks for the report @t-hamano!
