### ISSUE TITLE
Two bug fixes relating to image dimensions

### ISSUE THREAD

**Issue by smerriman** [darylldoyle/safe-svg#15]
I see you're possibly releasing a new version shortly, so I thought I'd highlight two bug fixes that really need to be in it. Given the plugin hasn't been updated in ages, I've been hacking them into versions I install, so don't want them to go back to being broken on upgrade.

a) https://wordpress.org/support/topic/1-9-9-doesnt-return-correct-width-and-height/

A missing string cast causes dimensions to be lost from some SVGs.

b) https://wordpress.org/support/topic/square-svgs-are-totally-broken-in-chrome/

A bug with srcsets breaks square SVGs entirely in Chrome.

**Comment by jeffpaul** [comment]
@smerriman do you happen to have code changes you could propose in a pull request for us to review for inclusion in an upcoming release?

**Comment by mehulkaklotar** [comment]
Hi @smerriman 

- https://wordpress.org/support/topic/1-9-9-doesnt-return-correct-width-and-height/ --> For this issue, we have already put checks for width and height in current version of code. https://github.com/10up/safe-svg/blob/develop/safe-svg.php#L429 Can you share the svg that you are trying here?
- https://wordpress.org/support/topic/square-svgs-are-totally-broken-in-chrome/ --> For srcset to remove from the code, we are not really sure to just remove them for all svgs files. We don't want to compromise other svgs which was not uploaded using safe svg. We have removed the double slashes being added to the svg file url in this commits.  https://github.com/10up/safe-svg/pull/19/commits/97f4700f1e126b6660de597dd0a3f6d936f0b7a9 https://github.com/10up/safe-svg/pull/19/commits/640fefb6cfdb516a5bd8d226342bfe603e255a4f

**Comment by smerriman** [comment]
Apologies for not getting back to you sooner.

Yes, that check is flawed as mentioned in the bug report. `is_numeric( $attributes->width )` is guaranteed to return false, because `$attributes->width` is of type `object(SimpleXMLElement)`, which never passes as numeric.

Try it with any SVG that has a width and height set but no viewbox (or does have a viewbox by adding debugging info into the plugin) and you'll see the first check always fails.

I can still replicate the fact the svgs with srcsets are fully broken in Chrome; will need a little more time to see why they were being added in WordPress.

**Comment by smerriman** [comment]
See https://jsfiddle.net/f6seL3g4/ for an example, where I've uploaded a test SVG file to our server which has a width/height of 200 and viewbox set to 0 0 32 32.

Firstly, if you view in Chrome, you'll see it's very small, while in Firefox at least it's 200px wide as expected. Works fine without the srcset. Again, that's probably a Chrome bug, but having a srcset in the first place is bad.

Secondly, if you download that SVG file and upload with Safe SVG, you'll see it uses 32x32, ignoring the 200x200 due to the typecasting error.
