### ISSUE TITLE
PHP 8.3 compatibility

### ISSUE THREAD

**Issue by rolf-yoast** [darylldoyle/safe-svg#210]
### Describe the bug

The plugin is using the ezyang/htmlpurifier library via composer. This library uses the `get_magic_quotes_gpc` function in https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Config.php.

1. But this function has been removed in PHP 8.0

### Steps to Reproduce

1. Go to https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Config.php
2. Search for `get_magic_quotes_gpc` and you can find it multiple times in the code
3. Check https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylldoyle** [comment]
@jeffpaul the new versions of the `svg-sanitizer` library dropped the use of the `ezyang/htmlpurifier` library. Updating `enshrined/svg-sanitize` to the latest version will solve this issue.

**Comment by rolf-yoast** [comment]
@sksaju I see you've made a PR for this, thanks for that. But when will this be released? Any estimate on the ETA?

**Comment by jeffpaul** [comment]
@rolf-yoast there's some code review feedback on the linked PR that need to be resolved first, then we otherwise do a monthly check across our FOSS plugins to see which have something releasable.  So unlikely that we see this get released until later in September at the earliest.
