### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by jeffpaul** [darylldoyle/safe-svg#22]
**Is your enhancement related to a problem? Please describe.**
Now that WordPress 5.9 is released, we'll want to test Safe SVG to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Safe SVG on WordPress 5.9
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: #13.

**Comment by cadic** [comment]
@jeffpaul Tested with WordPress 5.9
- [x] Plugin activate/deactivate
- [x] Create new post with Image block, SVG uploaded
- [x] Add SVG to post thumbnail
