### ISSUE TITLE
Change block category to be one of the core defaults 

### ISSUE THREAD

**Issue by fabiankaegy** [darylldoyle/safe-svg#223]
Currently the "Inline SVG" block bundled with this plugin shows under the "Uncategorized" category in the block inserter. This is because the category is set to `safe-svg-blocks`:

https://github.com/10up/safe-svg/blob/c0e180deb45c62ac8f736fb13ce4072e2a532aa5/includes/blocks/safe-svg/block.json#L8

We should change this to use one of the core categories. 

My recommendation would be `design`

**Comment by kirtangajjar** [comment]
@dkotter Created a PR for it - https://github.com/10up/safe-svg/pull/226. It can be CRed now.
