### ISSUE TITLE
Wrong version number for enshrined/svg-sanitize in changelog.md

### ISSUE THREAD

**Issue by j-hoffmann** [darylldoyle/safe-svg#37]
It is just a documentation issue, but in the changelog it states:

> Update `enshrined/svg-sanitize` from 0.13.3 to 0.5.2 [...]

Obviously version 0.5.2 doesn't seem to be right. I guess this should be 0.15.4 (according to `composer.lock`).

**Comment by jeffpaul** [comment]
That should be v0.15.2, I'll update accordingly, thanks @j-hoffmann!

**Comment by j-hoffmann** [comment]
^0.15.2 is what is required in composer.json, but composer.lock states 0.15.4 was used. And from what i saw in the code, 0.15.4 is what is actually bundled in the build.
