### ISSUE TITLE
Future plans for composer package

### ISSUE THREAD

**Issue by roborourke** [darylldoyle/safe-svg#40]
Hey, great to see 10up taking on maintenance here! I was wondering what if any plans you might have for the future in terms of this plugin being on packagist.org. Will you be updating the name and resubmitting?

Also I noticed that 1.9.10 seems like it shouldn't really be a patch release if there are breaking changes with regards to WP and PHP version support. Not suggesting removing that tag of course but wanted to note it could cause problems for people using a loose enough version constraint.

**Comment by jeffpaul** [comment]
@roborourke are you able to use https://www.wpackagist.org/search?q=safe-svg&type=any&search=?

**Comment by roborourke** [comment]
Unfortunately not as only root level `composer.json` files can specify other repositories. Would make life a lot easier if we could!

This repo is still syncing to packagist.org at the moment so no issues there but if the package name changes it will stop. If you're not intending to continue supporting packagist.org too that's absolutely fine of course, just something I'd have to plan for.

**Comment by richardnadj** [comment]
I think this might be where I got the following error from [which I commented a commit regarding](https://github.com/10up/safe-svg/commit/72809740940cc7553867ec9651412fdab7970db2).

> You appear to be running a development version of Safe SVG. Please run composer install in order for things to work properly.

I have loaded the plugin `darylldoyle/safe-svg` directly from packagist in the past but I just tried now to load the package from wpackagist and the error disappeared. So problem solved for me.

**Comment by andronocean** [comment]
I got the same warning as @coalescecreate, actually — looks like that is quite intentional now since the autoloader isn't being generated on a normal `composer require`. I switched to wpackagist too to solve it.

I'm also a Bedrock user, so I would _slightly_ prefer the option of getting the plugin directly from packagist and installing it with my root Composer, if you're able to make that work at some point. Less overhead that way. If not though, it's not a big deal.

**Comment by jeffpaul** [comment]
Seems like easiest path here is to get @darylldoyle to add the @10up account as a maintainer on https://packagist.org/packages/darylldoyle/safe-svg and then tidying up the fields in https://github.com/10up/safe-svg/blob/develop/composer.json to match 10up's base set of fields used (though no strong need on my end to change from `darylldoyle/safe-svg` to, say, `10up/safe-svg` as long as 10up has the ability to continue pushing updates out to packagist is most important).

**Comment by darylldoyle** [comment]
@jeffpaul 10up have now been added as a maintainer of packagist 🙂  Let me know if you need anything else from me!

**Comment by jeffpaul** [comment]
@roborourke looks like today's 2.0.0 release made it out to https://packagist.org/packages/darylldoyle/safe-svg.  Does that suffice for what you were looking for or was there something else I could assist with?

**Comment by roborourke** [comment]
@jeffpaul not exactly, If you're not changing the package name then the packagist.org sync will continue just fine, however installs from packagist are broken now since the changes in the 1.9.10 patch release.

I think given the breakage it makes sense to change it to `10up/safe-svg` and not resubmit to packagist.org but point people to wpackagist instead perhaps.

Otherwise if you do intend to support installs from packagist.org it'll need to be fixed, though I totally get that the effort probably isn't worth it for you. If you do want to support packagist installs still I could take a stab at making a PR for it.

I'd consider removing the broken tags from packagist in the meantime.

**Comment by peterwilsoncc** [comment]
Hi @roborourke, fancy meeting you here 👋 

I suspect the issue is caused by 72809740940cc7553867ec9651412fdab7970db2 but I haven't had the chance to test it.

I think a pull request would be most helpful, maybe something like:

```php
if ( is_readable( __DIR__ . '/vendor/autoload.php' ) ) {
	require __DIR__ . '/vendor/autoload.php';
} elseif ( ! is_callable( 'some callable in enshrined/svg-sanitize' ) ) {
  // Show notice.
  return;
}
```

This ought to help in any sites you may have that install plugins via composer.

**Comment by roborourke** [comment]
Thanks @jeffpaul :)
