### ISSUE TITLE
Undefined variable: viewbox_width in safe-svg.php#L507

### ISSUE THREAD

**Issue by odil-io** [darylldoyle/safe-svg#54]
### Describe the bug

Today I imported a large about of files and SVG's from a `prod`-site to a `local`-site.
During that process the plugin gave some warnings. Most of them where:

> Notice: Undefined variable: viewbox_width in /Users/username/local-sites/domain/app/public/wp-content/plugins/safe-svg/safe-svg.php on line 507

[safe-svg.php#L507](https://github.com/10up/safe-svg/blob/develop/safe-svg.php#L507)

### Steps to Reproduce

Unknown. I assume it's because one or more svg's is missing a viewbox attribute.

### Screenshots, screen recording, code snippet

<img width="867" alt="Screenshot 2022-04-13 at 15 28 36" src="https://user-images.githubusercontent.com/2929078/163191671-1fce5a23-e753-4cf8-a471-6d09f3d85b9b.png">(private information obfuscated)

[safe-svg.php#L507](https://github.com/10up/safe-svg/blob/develop/safe-svg.php#L507)

### Environment information

Device: MacBook Pro M1
OS: macOS Monterey 12.3.1
Browser: Chrome 100.0.4896.75 (Official Build) (arm64)

### WordPress information

`
### wp-core ###

version: 5.9.3
site_language: nl_NL
user_language: nl_NL
timezone: Europe/Amsterdam
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 6
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/customer/www/domain.tld/public_html
wordpress_size: 52,16 MB (54696619 bytes)
uploads_path: /home/customer/www/domain.tld/public_html/wp-content/uploads
uploads_size: 266,52 MB (279462198 bytes)
themes_path: /home/customer/www/domain.tld/public_html/wp-content/themes
themes_size: 118,94 MB (124716088 bytes)
plugins_path: /home/customer/www/domain.tld/public_html/wp-content/plugins
plugins_size: 79,97 MB (83857959 bytes)
database_size: 41,70 MB (43728896 bytes)
total_size: 559,29 MB (586461760 bytes)

### wp-active-theme ###

name: PRIVATE/OBFUSCATED
version: 1.0.3
author: Pronamic
author_website: https://www.pronamic.eu/
parent_theme: none
theme_features: core-block-patterns, block-templates, widgets-block-editor, automatic-feed-links, html5, title-tag, custom-logo, align-wide, menus, post-thumbnails, editor-style, widgets
theme_path: /home/customer/www/domain.tld/public_html/wp-content/themes/theme
auto_update: Uitgeschakeld

### wp-themes-inactive (2) ###

Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates uitgeschakeld
WedWiki: version: 1.0.79, author: Pronamic, Auto-updates uitgeschakeld

### wp-mu-plugins (1) ###

InfiniteWP - Client Loader: author: Revmakx, version: (undefined)

### wp-plugins-active (15) ###

ACF Content Analysis for Yoast SEO: version: 3.0.1, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast, Auto-updates uitgeschakeld
Advanced Custom Fields PRO: version: 5.12.2, author: Delicious Brains, Auto-updates uitgeschakeld
Akismet Anti-Spam: version: 4.2.2, author: Automattic, Auto-updates uitgeschakeld
Gravity Forms: version: 2.6.1, author: Gravity Forms, Auto-updates uitgeschakeld
InfiniteWP - Client: version: 1.9.6, author: Revmakx, Auto-updates uitgeschakeld
Members: version: 3.1.7, author: MemberPress, Auto-updates uitgeschakeld
Post Types Order: version: 1.9.8, author: Nsp Code, Auto-updates uitgeschakeld
Pretty Links: version: 3.2.4, author: Pretty Links, Auto-updates uitgeschakeld
Pronamic Client: version: 1.9.4, author: Pronamic, Auto-updates uitgeschakeld
SiteGround Optimizer: version: 7.0.9, author: SiteGround, Auto-updates uitgeschakeld
SiteGround Security: version: 1.2.7, author: SiteGround, Auto-updates uitgeschakeld
SVG Support: version: 2.4.2, author: Benbodhi, Auto-updates uitgeschakeld
User Switching: version: 1.5.8, author: John Blackbourn & contributors, Auto-updates uitgeschakeld
Yoast SEO: version: 18.5.1, author: Team Yoast, Auto-updates uitgeschakeld
Yoast SEO Premium: version: 18.3, author: Team Yoast, Auto-updates uitgeschakeld

### wp-plugins-inactive (1) ###

Casino Features: version: 1.0.0, author: Author Name, Auto-updates uitgeschakeld

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
imagick_version: Niet beschikbaar
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.4.28 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.66.0 OpenSSL/1.1.1n-fips
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32-35-log
client_version: mysqlnd 7.4.28
max_allowed_packet: 33554432
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/customer/www/domain.tld/public_html/wp-content
WP_PLUGIN_DIR: /home/customer/www/domain.tld/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Ongedefinieerd
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@odil-io Thanks for the report. I believe this is the same issue we saw reported on the WordPress.org Forums and for which we have a PR up to fix: #51. If you have any time to test that PR to ensure that fixes your problem, that would be great. Thanks!

**Comment by odil-io** [comment]
Just tested it with the same local install and same .xml file, worked flawlessly!
Thank you for fixing!
