### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [darylldoyle/safe-svg#55]
Is your enhancement related to a problem? Please describe.
Now that WordPress 6.0 is released, we'll want to test Safe SVG to see if any incompatibility issues arise.

Describe the solution you'd like

- [ ] test Safe SVG on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #22, #13.

**Comment by jeffpaul** [comment]
Note that we'll likely want to keep an eye on how https://github.com/WordPress/gutenberg/issues/40963 evolves and if that impacts Safe SVG in any way
