### ISSUE TITLE
Remove plugin page "Upgrade" action link

### ISSUE THREAD

**Issue by mitchellknight** [darylldoyle/safe-svg#59]
### Is your enhancement related to a problem? Please describe.

The Upgrade action link on the WordPress plugins page links here: https://wpsvg.com/?utm_source=plugin-list&utm_medium=upgrade-link&utm_campaign=plugin-list&utm_content=action-link

According to that page:

> My spare time is completely full at the moment and as such WP SVG is no longer on sale to the public. Those with current licences can continue to use it and will be supported, but no new licences will be sold for the time being.

Since it's no longer for sale you don't need an Upgrade link.

### Designs

N/A

### Describe alternatives you've considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Good call out @mitchellknight, thank you!
