### ISSUE TITLE
Extra space in Featured Image

### ISSUE THREAD

**Issue by AdamWills** [darylldoyle/safe-svg#62]
### Describe the bug

When adding an SVG as a Featured Image, there is extra padding that appears above the featured image.

This seems to be related to some CSS that is added to this plugin.

### Steps to Reproduce

1. Go to any page.
2. Add an SVG as a Featured Image
3. Note the extra space.

### Screenshots, screen recording, code snippet

Without the plugin enabled:
<img width="278" alt="Screen Shot 2022-05-17 at 8 58 09 AM" src="https://user-images.githubusercontent.com/3680753/168816705-cf07f523-c989-45fd-a470-822b6e0e080f.png">

With the plugin enabled:
<img width="279" alt="Screen Shot 2022-05-17 at 8 57 39 AM" src="https://user-images.githubusercontent.com/3680753/168816747-b3082b5d-b630-4b42-983a-025b68fff379.png">

The problematic code in question:
```
/**
 * Fix for Gutenberg not showing featured images correctly.
 */
img.components-responsive-wrapper__content[src$=".svg"] {
    position: relative;
}
```

### Environment information

- WordPress 5.9.3
- Chrome 101.0.4951.64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@AdamWills Thanks for the report and all the helpful details. I've opened a PR to address this, if you have time to review and test, that would be great. Thanks!
