### ISSUE TITLE
SVGO Optimisation

### ISSUE THREAD

**Issue by jeffpaul** [darylldoyle/safe-svg#68]
### Is your enhancement related to a problem? Please describe.

Port in from [Pro version](https://github.com/10up/wpsvg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gsarig** [comment]
@jeffpaul 
the pro plugin uses [svgo.wpsvg.com](http://svgo.wpsvg.com/) to check for a valid license ([here](https://github.com/10up/wpsvg/blob/6777d9a9ade605f198239135cae8f0224dababd5/includes/class-wpsvg-sanitiser.php#L212)) and send the svg file to their server to optimize. To avoid sending to another server, another approach is to use [SVGO](https://www.npmjs.com/package/svgo), which seems to be the tool that the pro plugin uses anyway. 
 
A Draft PR has been added here: https://github.com/10up/safe-svg/pull/79 and the results are promising. Currently, the optimization works for files uploaded via the Media Library, but not yet when uploaded directly (hence the "draft" status of the PR).

**Comment by jeffpaul** [comment]
@gsarig would be good to note on the PR if you're hoping to handle the direct upload work in the PR or if you'd prefer someone else to help finish that and bring the PR out of draft?

**Comment by gsarig** [comment]
@jeffpaul I've updated the PR, mentioning that I will resume my work with the first chance, to handle direct uploads as well.

**Comment by gsarig** [comment]
@jeffpaul As promised, PR has been updated with support for optimizing direct uploads.
