### ISSUE TITLE
NPM archive related scripts include node_modules and vendor files in zip.

### ISSUE THREAD

**Issue by peterwilsoncc** [darylldoyle/safe-svg#97]
### Describe the bug

When building an archive using the NPM `archive` and `postarchive` scripts, the `node_modules` and `vendor` folders are included in the zip file.

In local testing, this created a 69.6 MB zip file.

### Steps to Reproduce

1. Check out develop branch.
2. Run `npm i; composer i; npm run build;`
3. Run `npm run archive` -- observe the node and vendor folders are included in the zip
4. Run `npm run postarchive`
5. Run `cd safe-svg; ls`
6. Observe the unzipped files also include the node_modules and vendor folders

### Environment information

- Device: macbook pro 2020
- OS: macOS 12.6.2

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@peterwilsoncc any recommended resolution here?

**Comment by peterwilsoncc** [comment]
It looks like the following needs to be added to the composer config. The catch is that it isn't possible to included the vendor directory as we have a mix of dev and production dependencies. If the archive function is run while the dev dependencies are installed, the file will still be quite large.
```json
	"archive": {
		"exclude": [
			"/.distignore",
			"/.github",
			"/.gitignore",
			"/.wordpress-org",
			"/.wp-env.json",
			"/.wp-env.override.json",
			"/CHANGELOG.md",
			"/CODE_OF_CONDUCT.md",
			"/composer.json",
			"/composer.lock",
			"/CONTRIBUTING.md",
			"/CREDITS.md",
			"/package-lock.json",
			"/package.json",
			"/phpcs.xml",
			"/phpunit.xml.dist",
			"/README.md",
			"/webpack.config.js",
			"/node_modules",
			"/tests"
		]
```

**Comment by szepeviktor** [comment]
The same error if installed as a Composer package (GitHub ZIP contains development files).

We should use gitattributes/export-ignore as `composer archive` respects that.

**Comment by szepeviktor** [comment]
> We should use gitattributes/export-ignore

Oh no! This solves only the git index part of the problem.
`composer archive` works on the filesystem and adds everything to the zip file.
